### ISSUE TITLE
Thinking out loud...

### ISSUE THREAD

**Issue by idibidiart** [samuelli/bot-render#14]
Hi 

I'm trying to wrap my mind around the significance of this project, and I'd like to get your feedback on my thinking about it, in case I'm missing something.
 
EDITED:

I have a React app that I wish to expose to search bots (for SEO.) I don’t believe in using SSR because it negates the scalability we get with Single Page Apps (SPAs) where we do all the CPU-bound work of rendering the page on the client as opposed to doing it on a shared server, where the most common scenario involves NodeJS as the server, a single-threaded, cooperative multitasking environment that is designed for I/O-bound work.

One of the alternatives I‘ve considered is as follows:

Upon receiving a request for a given URL, the server loads the index.html file into a string and inject into it all JSON and text data (as JS var declarations) for the initial requested route (which is specified in the hash fragment of the URL, including any query params), text data (into off-screen HTML intended for the bot) and the corresponding HTML meta tags. This way when the SPA is loaded by the browser the initial route will already have the data it needs, and will start rendering without having to wait for the data, so the initial render will feel fast since the browser won’t open a blank page then wait then render. Instead, it will open a blank page then immediately render, so the user won’t even see the blank page. In addition, the search bots will have the text content (in the off-screen div) and the meta tags to go along with the content. After the initial requested route is served, the SPA takes over.

The other alternative is to detect the user-agent and if it’s a bot then queue the request to a pool of Headless Chrome instances that will load the SPA like any user browser would, run it and return the HTML. The advantage is that my React app setup remains super simple and does not carry any server-side-rendering baggage.

Does my thinking on this make sense to you? What am I missing?

Thanks very much for sharing.

**Comment by samuelli** [comment]
> Upon receiving a request for a given URL, the server loads the index.html file into a string and inject into it all JSON and text data (as JS var declarations) for the initial requested route (which is specified in the hash fragment of the URL, including any query params), text data (into off-screen HTML intended for the bot) and the corresponding HTML meta tags. This way when the SPA is loaded by the browser the initial route will already have the data it needs, and will start rendering without having to wait for the data, so the initial render will feel fast since the browser won’t open a blank page then wait then render. Instead, it will open a blank page then immediately render, so the user won’t even see the blank page. In addition, the search bots will have the text content (in the off-screen div) and the meta tags to go along with the content. After the initial requested route is served, the SPA takes over.

You'll probably need to do some testing, but search engines typically don't like this approach since its easy to hack around. For example, to improve SEO scores, I might inject lots of keywords into a off-screen div. It's also a bunch of work you'll need to do which is very specific to your application (ie knowing what data you will need on the page).

> The other alternative is to detect the user-agent and if it’s a bot then queue the request to a pool of Headless Chrome instances that will load the SPA like any user browser would, run it and return the HTML. The advantage is that my React app setup remains super simple and does not carry any server-side-rendering baggage.

Yep, this is what this repo is. It's not production ready yet, but will hopefully be soon. See also my [Medium post](https://medium.com/@samdotli/solving-seo-with-headless-chrome-for-your-client-side-framework-288e66fdd2b7) on this. That's exactly the idea - solving this particular scenario with minimal change to your existing server (pre-SSR).

**Comment by idibidiart** [comment]
>  It's also a bunch of work you'll need to do which is very specific to your application (ie knowing what data you will need on the page).

Yes, I should have clarified that if you're using GraphQL to fetch the data for each route you're only dealing with data types and their resolver functions, and you set that up once for the entire app, i.e. it's route/page independent.

As to the off-screen div, it could be off-screen via a complex 'transform' not simply 'left: -1000px;' so there is really no way for the bot to interpret transforms and figure out if the div is visible to the user or not. I do think it can work.

I respect your work very much and may ultimately recommend its use in production (once it's ready) at major clients. However, I think I'd like to give the alternative I shared a shot (with GraphQL as the data provider) and see if that'll work because then I don't have to setup a separate rendering pipeline for bots.

**Comment by samuelli** [comment]
> As to the off-screen div, it could be off-screen via a complex 'transform' not simply 'left: -1000px;' so there is really no way for the bot to interpret transforms and figure out if the div is visible to the user or not. I do think it can work.

I'm not sure I understand this. A bot like googlebot uses a browser, so it is able to detect if it is onscreen.

**Comment by idibidiart** [comment]
Oh, I see. You are completely right. I forgot the context was a browser.

**Comment by idibidiart** [comment]
Thank you! Please let me know if you accept some donations. Would love to see this come to production ready state!
