### ISSUE TITLE
Docker container on Arch Linux: ECONNREFUSED

### ISSUE THREAD

**Issue by pkaske** [samuelli/bot-render#2]
Thanks for this awesome project. That's exactly what I've bee looking for. I just have problems getting this running with docker. I followed the steps in the readme to setup the docker container and used the same curl command to test the bot-render. I always got this output.

Seems like the express server can't connect to the chrome dev tools interface?!

```
{ Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
```

**Comment by samuelli** [comment]
What OS are you using? At the moment this was built for Ubuntu platforms and I assume chrome gets installed as `/usr/bin/google-chrome-beta`. Probably needs to be tuned for other platforms.

**Comment by samuelli** [comment]
Wait its docker hmm.

**Comment by samuelli** [comment]
Can you try `docker build -t bot-render-container --no-cache=true`? I just tried and I was having a (different) issue and that fixed it for me.

**Comment by pkaske** [comment]
Here what I tried just now
```sh
docker rm bot-render-container
docker build -t bot-render . --no-cache=true
docker run --name bot-render-container bot-render
docker exec bot-render-container curl http://localhost:8080/?url=https://dynamic-meta.appspot.com
```

The result remains the same.
I'm using `Docker version 17.05.0-ce, build 89658bed64`

Is there any more information I can give you?

**Comment by samuelli** [comment]
Hmm not sure what it is.
 * What OS are you using?
 * Can you run `docker exec bot-render-container curl http://localhost:9222/json/list` and `docker exec bot-render-container ls /usr/bin/google-chrome-beta`?

**Comment by pkaske** [comment]
I'm on Linux Arch (Antergos to be precise).
I opened a shell on the container and executed `ls -ahl /usr/bin/google-chrome-beta`.

Output:
`lrwxrwxrwx 1 root root 42 May 31 07:44 google-chrome-beta -> /opt/google/chrome-beta/google-chrome-beta`

Chrome is there. I then tried to start it manually in the shell of the container:

```sh
# /usr/bin/google-chrome-beta --headless --disable-gpu --remote-debugging-port=9222
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Trace/breakpoint trap (core dumped)
```

**Comment by pkaske** [comment]
I tried `--no-sandbox`. This seems to work. Chrome then starts and accepts requests.

```sh
# /usr/bin/google-chrome-beta --headless --disable-gpu --remote-debugging-port=9222 --no-sandbox
[0601/194042.967214:WARNING:audio_manager.cc(293)] Multiple instances of AudioManager detected
[0601/194042.967310:WARNING:audio_manager.cc(254)] Multiple instances of AudioManager detected
[0601/194042.967983:ERROR:devtools_http_handler.cc(759)] Error writing DevTools active port to file
libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted
```

Found that info here: https://github.com/jessfraz/dockerfiles/issues/65
To disable sandbox is of course not really a good thing to do...

**Comment by pkaske** [comment]
Seems the cause is that arch doesn't have userspaces enabled by default.
https://github.com/jessfraz/dockerfiles/issues/65#issuecomment-241536092

**Comment by samuelli** [comment]
I see, thanks for investigating!

If you want to disable sandbox in docker, you can add `--no-sandbox` flag to the config https://github.com/samuelli/bot-render/blob/master/chromium.js#L13
