### ISSUE TITLE
Explicit rendering flag

### ISSUE THREAD

**Issue by samuelli** [samuelli/bot-render#30]
Under consideration: Allow for a flag to notify when rendering is complete.

Need to find cases where the current loading function is insufficient. Do you have an example? Please comment below!

**Comment by paales** [comment]
As discussed in https://github.com/samuelli/bot-render/issues/48, there are some issues with fully relying on network idle time (as far as I understand how it works).

To trigger of some other stuff in our application (setting meta tags, etc.) we're currently dispatching a custom event in the router we're using. It might be a good idea if we could incorporate a new event that notifies the bot renderer the page is 'good enough' to be send, even though not all custom elements are fully loaded in terms of data (video's not fully downloaded, non important async stuff).

```js
this.dispatchEvent(new CustomEvent('page-loaded', { bubbles: true, composed: true } }));
```

Maybe this isn't the way to go an a better heuristic might be a better idea to keep the bot renderer dependency free (although it already isn't with the custom status codes).

**Comment by samuelli** [comment]
I like the event - I would make a slight change to `Event` instead of a `CustomEvent`.

**Comment by paales** [comment]
@samuelli Really cool!
