### ISSUE TITLE
Behave more like a true browser in terms of caching to improve performance.

### ISSUE THREAD

**Issue by paales** [samuelli/bot-render#51]
The current implementation fully disables all cache used, which makes the server side rendering slower than it could be. ([ref](https://github.com/samuelli/bot-render/blob/master/src/renderer.js#L21-L29))

The browsers cache can be utilised for faster page renders and cache invalidation would work exactly the same way other browsers would need to handle caching:
- Normally you can't flush the browser's cache
- Normally you can't disable the browser's cache
- Normally you can't disable service workers

How cache invalidation would work:
- If a service worker is installed it will automatically check on page-load if there is a new version available and will automatically fetch all the latest files.
- If it is a classic application, the application would implement cache-headers with additional asset-signing and the application would handle it's self.

**Comment by samuelli** [comment]
I think this is a good point and it'll result in faster page renders.

I'm not sure about the service worker one, your page should really work without a service worker. The really worrying part is service worker cause a lot of developmental pain, its hard to know which service worker you have or when it gets updated. If you push a bad service worker, it might get stuck there forever.

I think I'll reintroduce the browser cache but not the service worker.

**Comment by paales** [comment]
Hi Samuelli,

I'm not sure if I completely follow the argument, since the same argument applies to the browser, or am I missing something?

**Comment by samuelli** [comment]
It most definitely does. But this is a service you will be testing in development too, and its strictly intended to make the development story easier.

My experience with SW and from witnessing other people's experience is that when you do encounter an issue, it can be really painful and a huge time sink debugging that issue so I'd like to avoid yet another place where you have to worry about service workers and how that might be impacting inaccurate results etc.

As part of progressive enhancement, an application should work without a service worker, so I don't see any harm from disabling it either.

**Comment by paales** [comment]
Fair enough :)
